Add logging to diagnose an issue with hidden windows dialog
ogomez92/winWizard pull request #11
Opened 2024-01-07 19:48 UTC by jakubl7545

@lukaszgo1

2024-01-07 20:38 UTC, lukaszgo1 requested changes
This is a nice start! I'd suggest adding some more verbose logging into `splitToStacks`, to record what stacks are created, what windows end-up in a given stack and what finally gets yielded from this method. It is also helpful to be more descriptive in the logged info i.e. in addition to indexes log a textual description of what exactly is being logged. Note that while its fine to send it like this to the affected user, before this is merged to master we should make sure the info is logged at the debug level.

2024-01-08 15:03 UTC, jakubl7545 commented
@lukaszgo1 I've added more logging with descriptions. If it's good I'll send Wizard to the user who reported this bug and maybe something will come from it.

2024-01-08 16:06 UTC, lukaszgo1 reviewed
This is fine for sending to the user. When we will understand the cause I'll take another look before merging to master.

2024-03-22 16:29 UTC, lukaszgo1 reviewed
Please convert all `log.info` calls to `log.debug`.

2024-03-22 16:29 UTC, lukaszgo1 commented on addon/globalPlugins/winWizard.py
> -
Please re-introduce this empty line for readability.

2024-03-22 16:29 UTC, lukaszgo1 commented on addon/globalPlugins/winWizard.py
> +			log.info(f'Stacks with hidden windows: {sorted(set(slotsToStacks))}')
Please assign this to a variable - something like `stacksWithHiddenWindows` and then use it in the logging call, and in the loop below.

2024-03-22 16:29 UTC, lukaszgo1 commented on addon/globalPlugins/winWizard.py
>  				yield Stack(stackNumber, sorted(hiddenInCurrentStack, key=lambda slot: slot.presentationalNumber))
Same here i.e. assign into a variable, use it when logging and then finally yield.

2024-03-23 15:48 UTC, lukaszgo1 approved these changes
LGTM! Feel free to squash merge.

2024-03-23 15:53 UTC, merged